In [17]:
print("Hola desde ClinicAssist")

Hola desde ClinicAssist

In [18]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
conexion = psycopg2.connect(

    host="localhost",

    database="clinicassist_db",

    user="postgres",

    password="Aprendiendo123"

)

print("Conexión exitosa ✓")

NameError: name 'psycopg2' is not defined

:

In [ ]:
import psycopg2

conexion = psycopg2.connect(
    host="localhost",
    database="clinicassist_db",
    user="postgres",
    password="Aprendiendo123"
)

print("Conexión exitosa ✓")

Conexión exitosa ✓

In [ ]:
df_tratamientos = pd.read_sql("SELECT * FROM tratamientos", conexion)
df_tratamientos

C:\Users\snchz\AppData\Local\Temp\ipykernel_1496\3821799486.py:1: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tratamientos = pd.read_sql("SELECT * FROM tratamientos", conexion)

    tratamiento_id  cita_id            tipo   costo  completado
0                1        1        limpieza   650.0        True
1                2        2      ortodoncia  3500.0        True
2                3        3        limpieza   650.0        True
3                4        6      ortodoncia  3500.0        True
4                5        7      extraccion  1200.0        True
5                6        8        revision   400.0        True
6                7        9        limpieza   650.0        True
7                8       11        limpieza   650.0        True
8                9       12        revision   400.0        True
9               10       13        limpieza   800.0        True
10              11       15      endodoncia  4500.0        True
11              12       16      endodoncia  4500.0        True
12              13       17        revision   400.0        True
13              14       18      ortodoncia  3500.0        True
14              15       19      ortodoncia  1800.0        True
15              16       20        limpieza   650.0        True
16              17       21      endodoncia  4500.0        True
17              18       23        limpieza   650.0        True
18              19       24      ortodoncia  3500.0        True
19              20       25      endodoncia  4500.0        True
20              21       26        revision   400.0        True
21              22       27  blanqueamiento  2800.0        True
22              23       28      extraccion  1200.0        True
23              24       30  blanqueamiento  2800.0        True
24              25       31        limpieza   700.0        True
25              26       32      endodoncia  4500.0        True
26              27       34        revision   400.0        True
27              28       35        limpieza   700.0        True
28              29       36      endodoncia  4500.0        True
29              30       37        limpieza   650.0        True
30              31       38      extraccion  1200.0        True
31              32       39      ortodoncia  3500.0        True
32              33       40      endodoncia  4500.0        True
33              34       41        limpieza   650.0        True
34              35       42      extraccion  1200.0        True
35              36       43  blanqueamiento  2800.0        True
36              37       44        revision   400.0        True
37              38       45      ortodoncia  1800.0        True
38              39       46        limpieza   700.0        True
39              40       47      ortodoncia  1800.0        True
40              41       48      ortodoncia  1800.0        True
41              42       49        limpieza   650.0        True
42              43       50      endodoncia  4500.0        True
43              44       51  blanqueamiento  1400.0        True
44              45       52      ortodoncia  1800.0        True
45              46       53      endodoncia  4500.0        True
46              47       55      ortodoncia  1800.0        True

In [ ]:
pip install sqlalchemy

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: sqlalchemy in c:\users\snchz\appdata\roaming\python\python314\site-packages (2.0.48)
Requirement already satisfied: greenlet>=1 in c:\users\snchz\appdata\roaming\python\python314\site-packages (from sqlalchemy) (3.3.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\snchz\appdata\roaming\python\python314\site-packages (from sqlalchemy) (4.15.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sqlalchemy import create_engine

engine = create_engine("postgresql+psycopg2://postgres:Aprendiendo123@localhost/clinicassist_db")

print("Conexión con SQLAlchemy exitosa ✓")

Conexión con SQLAlchemy exitosa ✓

In [ ]:
df_tratamientos = pd.read_sql("SELECT * FROM tratamientos", engine)
df_tratamientos

    tratamiento_id  cita_id            tipo   costo  completado
0                1        1        limpieza   650.0        True
1                2        2      ortodoncia  3500.0        True
2                3        3        limpieza   650.0        True
3                4        6      ortodoncia  3500.0        True
4                5        7      extraccion  1200.0        True
5                6        8        revision   400.0        True
6                7        9        limpieza   650.0        True
7                8       11        limpieza   650.0        True
8                9       12        revision   400.0        True
9               10       13        limpieza   800.0        True
10              11       15      endodoncia  4500.0        True
11              12       16      endodoncia  4500.0        True
12              13       17        revision   400.0        True
13              14       18      ortodoncia  3500.0        True
14              15       19      ortodoncia  1800.0        True
15              16       20        limpieza   650.0        True
16              17       21      endodoncia  4500.0        True
17              18       23        limpieza   650.0        True
18              19       24      ortodoncia  3500.0        True
19              20       25      endodoncia  4500.0        True
20              21       26        revision   400.0        True
21              22       27  blanqueamiento  2800.0        True
22              23       28      extraccion  1200.0        True
23              24       30  blanqueamiento  2800.0        True
24              25       31        limpieza   700.0        True
25              26       32      endodoncia  4500.0        True
26              27       34        revision   400.0        True
27              28       35        limpieza   700.0        True
28              29       36      endodoncia  4500.0        True
29              30       37        limpieza   650.0        True
30              31       38      extraccion  1200.0        True
31              32       39      ortodoncia  3500.0        True
32              33       40      endodoncia  4500.0        True
33              34       41        limpieza   650.0        True
34              35       42      extraccion  1200.0        True
35              36       43  blanqueamiento  2800.0        True
36              37       44        revision   400.0        True
37              38       45      ortodoncia  1800.0        True
38              39       46        limpieza   700.0        True
39              40       47      ortodoncia  1800.0        True
40              41       48      ortodoncia  1800.0        True
41              42       49        limpieza   650.0        True
42              43       50      endodoncia  4500.0        True
43              44       51  blanqueamiento  1400.0        True
44              45       52      ortodoncia  1800.0        True
45              46       53      endodoncia  4500.0        True
46              47       55      ortodoncia  1800.0        True

In [ ]:
df_tratamientos.info()

<class 'pandas.DataFrame'>
RangeIndex: 47 entries, 0 to 46
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   tratamiento_id  47 non-null     int64
 1   cita_id         47 non-null     int64
 2   tipo            47 non-null     str
 3   costo           47 non-null     float64
 4   completado      47 non-null     bool
dtypes: bool(1), float64(1), int64(2), str(1)
memory usage: 1.6 KB

In [ ]:
# GRÁFICA 1 — Ingresos totales por tipo de tratamiento
ingresos = df_tratamientos.groupby('tipo')['costo'].sum().sort_values(ascending=False)

plt.figure(figsize=(8, 5))
sns.barplot(x=ingresos.values, y=ingresos.index, palette='Blues_r')
plt.title('Ingresos totales por tipo de tratamiento', fontsize=14, fontweight='bold')
plt.xlabel('Ingreso total (MXN)')
plt.ylabel('Tipo de tratamiento')
plt.tight_layout()
plt.show()

NameError: name 'df_tratamientos' is not defined

In [ ]:
import sys
!{sys.executable} -m pip install psycopg2-binary

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: psycopg2-binary in c:\users\snchz\appdata\roaming\python\python314\site-packages (2.9.12)

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip